#!/usr/bin/env python3
"""Build an explicit localhost-bound GitLab plugin marketplace for Codex use."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ID = "gitlab-self-hosted"
SOURCE_PLUGIN = ROOT / "plugins" / PLUGIN_ID
LOCAL_MCP_TEMPLATE = SOURCE_PLUGIN / "workspace-binding" / ".mcp.local.json.example"
DEFAULT_OUTPUT = ROOT / "dist" / "gitlab-local-marketplace"
GENERATED_MARKETPLACE_NAME = "ademkao-gitlab-local"
GENERATED_PLUGIN_RELATIVE = Path("plugins") / PLUGIN_ID
GENERATED_MARKETPLACE_RELATIVE = Path(".agents") / "plugins" / "marketplace.json"


def fail(message: str) -> "NoReturn":
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def ensure_safe_output(output: Path) -> Path:
    resolved = output.expanduser().resolve()
    source = SOURCE_PLUGIN.resolve()
    if resolved == source or source in resolved.parents:
        fail("output must not be inside the source plugin directory")
    if resolved == ROOT.resolve():
        fail("output must not replace the repository root")
    return resolved


def load_json(path: Path, description: str) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"unable to read {description}: {exc}")


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def build(output: Path, force: bool) -> None:
    if not SOURCE_PLUGIN.is_dir():
        fail(f"source plugin not found: {SOURCE_PLUGIN}")
    if not LOCAL_MCP_TEMPLATE.is_file():
        fail(f"local MCP template not found: {LOCAL_MCP_TEMPLATE}")

    output = ensure_safe_output(output)
    if output.exists():
        if not force:
            fail(f"output already exists: {output}; pass --force to replace it")
        shutil.rmtree(output)

    generated_plugin = output / GENERATED_PLUGIN_RELATIVE
    generated_plugin.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(SOURCE_PLUGIN, generated_plugin)

    manifest_path = generated_plugin / ".codex-plugin" / "plugin.json"
    manifest = load_json(manifest_path, "plugin manifest")
    if manifest.get("name") != PLUGIN_ID:
        fail(f"source plugin manifest name must be '{PLUGIN_ID}'")
    if "mcpServers" in manifest or "apps" in manifest:
        fail("portable plugin manifest must be endpoint-unbound")
    manifest["mcpServers"] = "./.mcp.json"
    write_json(manifest_path, manifest)

    mcp_manifest = load_json(LOCAL_MCP_TEMPLATE, "local MCP template")
    server = mcp_manifest.get("mcpServers", {}).get("gitlab")
    if not isinstance(server, dict) or server.get("url") != "http://127.0.0.1:3333/mcp":
        fail("local MCP template must define the expected localhost endpoint")
    write_json(generated_plugin / ".mcp.json", mcp_manifest)

    helper_dir = generated_plugin / "workspace-binding"
    if helper_dir.exists():
        shutil.rmtree(helper_dir)

    setup = {
        "profile": "local-mcp",
        "artifact_type": "local-mcp-marketplace",
        "workspace_specific_source": True,
        "binding_mode": "local-mcp",
        "plugin_id": PLUGIN_ID,
        "mcp_url": "http://127.0.0.1:3333/mcp",
        "marketplace_name": GENERATED_MARKETPLACE_NAME,
        "plugin_reference": f"{PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}",
        "source_portable_unbound": True,
        "endpoint_configured_explicitly": True,
        "requires_local_mcp_server": True,
    }
    write_json(generated_plugin / ".chatgpt-setup.json", setup)

    marketplace = {
        "name": GENERATED_MARKETPLACE_NAME,
        "interface": {"displayName": "AdemKao GitLab Self-Hosted Local"},
        "plugins": [
            {
                "name": PLUGIN_ID,
                "source": {"source": "local", "path": f"./plugins/{PLUGIN_ID}"},
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Developer Tools",
            }
        ],
    }
    write_json(output / GENERATED_MARKETPLACE_RELATIVE, marketplace)
    (output / "README.md").write_text(
        f"""# Generated GitLab Self-Hosted Local Marketplace

This directory was generated by `scripts/build_local_variant.py` for a Codex
client running on the same host as the bundled MCP server.

- Marketplace: `{GENERATED_MARKETPLACE_NAME}`
- Plugin reference: `{PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}`
- MCP endpoint: `http://127.0.0.1:3333/mcp`

The portable source plugin remains endpoint-unbound. Use this generated variant
only when the MCP server is intentionally running on the same machine.
""",
        encoding="utf-8",
    )

    print(f"Built local GitLab Self-Hosted marketplace: {output}")
    print(f"Plugin reference: {PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}")
    print("MCP URL: http://127.0.0.1:3333/mcp")
    print("The portable source plugin remains endpoint-unbound.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a localhost-bound GitLab Self-Hosted marketplace for local Codex use."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="marketplace-source output directory (default: dist/gitlab-local-marketplace)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace the output directory if it already exists",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    build(args.output, args.force)


if __name__ == "__main__":
    main()
