#!/usr/bin/env python3
"""Build a personal GitLab plugin marketplace with a remote MCP endpoint.

The portable source plugin keeps its localhost MCP fallback for local Codex
development. This helper creates a separate, user-specific marketplace source
whose copied plugin points at a validated public HTTPS MCP endpoint instead.
It does not require a ChatGPT App/connector ID or an OpenAI managed App.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from chatgpt_binding import BindingValidationError, validate_remote_mcp_url

ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ID = "gitlab-self-hosted"
SOURCE_PLUGIN = ROOT / "plugins" / PLUGIN_ID
DEFAULT_OUTPUT = ROOT / "dist" / "gitlab-remote-marketplace"
GENERATED_MARKETPLACE_NAME = "ademkao-gitlab-remote"
GENERATED_PLUGIN_RELATIVE = Path("plugins") / PLUGIN_ID
GENERATED_MARKETPLACE_RELATIVE = Path(".agents") / "plugins" / "marketplace.json"


def fail(message: str) -> "NoReturn":
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def ensure_safe_output(output: Path) -> Path:
    resolved = output.expanduser().resolve()
    source = SOURCE_PLUGIN.resolve()
    if resolved == source or source in resolved.parents:
        fail("output must not be inside the source plugin directory")
    if resolved == ROOT.resolve():
        fail("output must not replace the repository root")
    return resolved


def load_json(path: Path, description: str) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"unable to read {description}: {exc}")


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def generated_readme(mcp_url: str) -> str:
    return f"""# Generated GitLab Self-Hosted Remote Marketplace

This directory was generated by `scripts/build_personal_variant.py` for a
personal remote MCP deployment.

- Marketplace: `{GENERATED_MARKETPLACE_NAME}`
- Plugin reference: `{PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}`
- Remote MCP endpoint: `{mcp_url}`

The generated plugin keeps `mcpServers: \"./.mcp.json\"`, with `.mcp.json`
pointing at the remote HTTPS endpoint. The client performs the server's OAuth
discovery and GitLab authorization flow when the plugin is first used.

This artifact does not contain a workspace App binding, does not require an
App/connector ID, and is not an OpenAI managed App Template. Keep this
workspace-specific marketplace source private when its endpoint is private to
your organization.
"""


def build(mcp_url: str, output: Path, force: bool) -> None:
    if not SOURCE_PLUGIN.is_dir():
        fail(f"source plugin not found: {SOURCE_PLUGIN}")

    try:
        mcp_url = validate_remote_mcp_url(mcp_url)
    except BindingValidationError as exc:
        fail(str(exc))

    output = ensure_safe_output(output)
    if output.exists():
        if not force:
            fail(f"output already exists: {output}; pass --force to replace it")
        shutil.rmtree(output)

    generated_plugin = output / GENERATED_PLUGIN_RELATIVE
    generated_plugin.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(SOURCE_PLUGIN, generated_plugin)

    helper_dir = generated_plugin / "workspace-binding"
    if helper_dir.exists():
        shutil.rmtree(helper_dir)

    mcp_path = generated_plugin / ".mcp.json"
    mcp_manifest = load_json(mcp_path, "portable MCP manifest")
    server = mcp_manifest.get("mcpServers", {}).get("gitlab")
    if not isinstance(server, dict):
        fail("portable MCP manifest must define mcpServers.gitlab")
    server["url"] = mcp_url
    write_json(mcp_path, mcp_manifest)

    manifest_path = generated_plugin / ".codex-plugin" / "plugin.json"
    manifest = load_json(manifest_path, "plugin manifest")
    if manifest.get("name") != PLUGIN_ID:
        fail(f"source plugin manifest name must be '{PLUGIN_ID}'")
    if manifest.get("mcpServers") != "./.mcp.json":
        fail("portable plugin manifest must point to ./.mcp.json")
    manifest.pop("apps", None)
    write_json(manifest_path, manifest)

    setup = {
        "profile": "personal-remote-mcp",
        "artifact_type": "remote-mcp-marketplace",
        "workspace_specific_source": True,
        "binding_mode": "remote-mcp",
        "plugin_id": PLUGIN_ID,
        "mcp_url": mcp_url,
        "marketplace_name": GENERATED_MARKETPLACE_NAME,
        "plugin_reference": f"{PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}",
        "requires_chatgpt_app_binding": False,
        "requires_explicit_oauth": True,
        "source_local_mcp_replaced": True,
        "doctor_command": f"python3 scripts/chatgpt_mcp_doctor.py --mcp-url {mcp_url}",
    }
    write_json(generated_plugin / ".chatgpt-setup.json", setup)

    marketplace = {
        "name": GENERATED_MARKETPLACE_NAME,
        "interface": {"displayName": "AdemKao GitLab Self-Hosted Remote"},
        "plugins": [
            {
                "name": PLUGIN_ID,
                "source": {"source": "local", "path": f"./plugins/{PLUGIN_ID}"},
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Developer Tools",
            }
        ],
    }
    write_json(output / GENERATED_MARKETPLACE_RELATIVE, marketplace)
    (output / "README.md").write_text(generated_readme(mcp_url), encoding="utf-8")

    print(f"Built personal GitLab Self-Hosted remote marketplace: {output}")
    print(f"Plugin reference: {PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}")
    print(f"Remote MCP URL: {mcp_url}")
    print("The portable source plugin and localhost MCP fallback were not modified.")
    print("The generated plugin does not require a ChatGPT App/connector ID.")
    print("Import/install this generated marketplace before using its plugin reference.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a personal GitLab Self-Hosted marketplace bound directly to "
            "a remote HTTPS MCP endpoint."
        )
    )
    parser.add_argument(
        "--mcp-url",
        required=True,
        help="public HTTPS /mcp endpoint",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="marketplace-source output directory (default: dist/gitlab-remote-marketplace)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace the output directory if it already exists",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    build(args.mcp_url, args.output, args.force)


if __name__ == "__main__":
    main()
