#!/usr/bin/env python3
"""Build a workspace-specific GitLab Self-Hosted ChatGPT marketplace source.

This repository helper binds an already-created ChatGPT workspace app/connector
ID into a copied plugin variant. It is not an OpenAI managed App Template.

The portable source plugin is intentionally endpoint-unbound. The generated
artifact is a standalone marketplace source whose plugin copy is App-bound and
contains no direct MCP server definition.

The package identifier is intentionally `gitlab-self-hosted`, not `gitlab`, to
avoid collision with OpenAI's curated GitLab plugin. Generating the artifact does
not modify an already-installed ChatGPT plugin; the artifact must become the
marketplace source that the target client/workspace actually imports or installs.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

from chatgpt_binding import BindingValidationError, validate_remote_mcp_url

ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ID = "gitlab-self-hosted"
SOURCE_PLUGIN = ROOT / "plugins" / PLUGIN_ID
DEFAULT_OUTPUT = ROOT / "dist" / "gitlab-chatgpt-marketplace"
WORKSPACE_BINDING_TEMPLATE = SOURCE_PLUGIN / "workspace-binding" / ".app.json.example"
PLACEHOLDER = "REPLACE_WITH_GITLAB_APP_OR_CONNECTOR_ID"
APP_ID_PATTERN = re.compile(r"^[A-Za-z0-9_.:-]+$")
GENERATED_MARKETPLACE_NAME = "ademkao-gitlab-chatgpt"
GENERATED_PLUGIN_RELATIVE = Path("plugins") / PLUGIN_ID
GENERATED_MARKETPLACE_RELATIVE = Path(".agents") / "plugins" / "marketplace.json"


def fail(message: str) -> "NoReturn":
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def validate_app_id(value: str) -> str:
    app_id = value.strip()
    if not app_id or app_id == PLACEHOLDER:
        fail("provide a real ChatGPT workspace app/connector ID")
    if len(app_id) > 256:
        fail("app/connector ID is unexpectedly long")
    if not APP_ID_PATTERN.fullmatch(app_id):
        fail("app/connector ID contains unsupported characters")
    return app_id


def ensure_safe_output(output: Path) -> Path:
    resolved = output.expanduser().resolve()
    source = SOURCE_PLUGIN.resolve()
    if resolved == source or source in resolved.parents:
        fail("output must not be inside the source plugin directory")
    if resolved == ROOT.resolve():
        fail("output must not replace the repository root")
    return resolved


def load_json(path: Path, description: str) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"unable to read {description}: {exc}")


def write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def generated_readme(app_id: str, mcp_url: str) -> str:
    return f"""# Generated GitLab Self-Hosted ChatGPT Marketplace Source

This directory was generated by `scripts/build_chatgpt_variant.py` for one
ChatGPT workspace/App binding.

- Marketplace: `{GENERATED_MARKETPLACE_NAME}`
- Plugin reference: `{PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}`
- Remote MCP endpoint configured on the App: `{mcp_url}`
- Workspace App/connector ID: `{app_id}`

## Important

Generating this directory does **not** update or replace an already-installed
`gitlab@ademkao-codex-plugins` plugin. That old package identifier collides with
the OpenAI-curated GitLab plugin and is deprecated for this repository.

The portable v0.5.4+ package reference is:

`{PLUGIN_ID}@ademkao-codex-plugins`

The portable package is endpoint-unbound. To use a remote ChatGPT MCP endpoint,
create/configure the custom MCP App first, then make this generated directory the
marketplace source that the target client/workspace actually imports or installs:

`{PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}`

For a shared ChatGPT workspace, keep workspace-specific App/connector IDs in an
appropriate private or controlled marketplace source unless their portability is
explicitly documented.

The generated `plugins/{PLUGIN_ID}/.codex-plugin/plugin.json` uses
`apps: \"./.app.json\"` and intentionally contains no `mcpServers`; the generated
plugin also contains no `.mcp.json`.

This helper output is not an OpenAI managed App Template and does not create,
publish, connect, or authorize the underlying ChatGPT App by itself.
"""


def build(app_id: str, mcp_url: str, output: Path, force: bool) -> None:
    if not SOURCE_PLUGIN.is_dir():
        fail(f"source plugin not found: {SOURCE_PLUGIN}")
    if not WORKSPACE_BINDING_TEMPLATE.is_file():
        fail(f"workspace binding helper template not found: {WORKSPACE_BINDING_TEMPLATE}")

    try:
        mcp_url = validate_remote_mcp_url(mcp_url)
    except BindingValidationError as exc:
        fail(str(exc))

    output = ensure_safe_output(output)
    if output.exists():
        if not force:
            fail(f"output already exists: {output}; pass --force to replace it")
        shutil.rmtree(output)

    generated_plugin = output / GENERATED_PLUGIN_RELATIVE
    generated_plugin.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(SOURCE_PLUGIN, generated_plugin)

    app_manifest = load_json(WORKSPACE_BINDING_TEMPLATE, "workspace binding helper template")
    gitlab_binding = app_manifest.get("apps", {}).get(PLUGIN_ID)
    if not isinstance(gitlab_binding, dict) or gitlab_binding.get("id") != PLACEHOLDER:
        fail("workspace binding helper template does not contain the expected placeholder")
    gitlab_binding["id"] = app_id

    helper_dir = generated_plugin / "workspace-binding"
    if helper_dir.exists():
        shutil.rmtree(helper_dir)

    write_json(generated_plugin / ".app.json", app_manifest)

    manifest_path = generated_plugin / ".codex-plugin" / "plugin.json"
    manifest = load_json(manifest_path, "plugin manifest")
    if manifest.get("name") != PLUGIN_ID:
        fail(f"source plugin manifest name must be '{PLUGIN_ID}'")
    if "mcpServers" in manifest or "apps" in manifest:
        fail("portable plugin manifest must be endpoint-unbound")
    manifest["apps"] = "./.app.json"
    write_json(manifest_path, manifest)

    generated_mcp = generated_plugin / ".mcp.json"
    if generated_mcp.exists():
        generated_mcp.unlink()

    setup = {
        "profile": "workspace-binding-helper",
        "artifact_type": "chatgpt-marketplace",
        "workspace_specific_source": True,
        "binding_mode": "app",
        "plugin_id": PLUGIN_ID,
        "mcp_url": mcp_url,
        "app_id": app_id,
        "marketplace_name": GENERATED_MARKETPLACE_NAME,
        "plugin_reference": f"{PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}",
        "workspace_binding_helper_only": True,
        "not_openai_managed_app_template": True,
        "requires_existing_workspace_app_or_connector": True,
        "requires_explicit_chatgpt_app_creation": True,
        "requires_marketplace_import_or_install": True,
        "does_not_modify_existing_installation": True,
        "source_portable_unbound": True,
        "endpoint_configured_on_app": True,
        "doctor_command": f"python3 scripts/chatgpt_mcp_doctor.py --mcp-url {mcp_url}",
    }
    write_json(generated_plugin / ".chatgpt-setup.json", setup)

    marketplace = {
        "name": GENERATED_MARKETPLACE_NAME,
        "interface": {"displayName": "AdemKao GitLab Self-Hosted ChatGPT"},
        "plugins": [
            {
                "name": PLUGIN_ID,
                "source": {"source": "local", "path": f"./plugins/{PLUGIN_ID}"},
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Developer Tools",
            }
        ],
    }
    write_json(output / GENERATED_MARKETPLACE_RELATIVE, marketplace)
    (output / "README.md").write_text(generated_readme(app_id, mcp_url), encoding="utf-8")

    print(f"Built workspace-specific GitLab Self-Hosted marketplace source: {output}")
    print(f"Plugin reference: {PLUGIN_ID}@{GENERATED_MARKETPLACE_NAME}")
    print(f"Remote MCP URL configured on App: {mcp_url}")
    print("The portable repository marketplace remains endpoint-unbound.")
    print("The generated marketplace selects an App-bound plugin with no direct MCP dependency.")
    print("The target workspace app/connector must already exist and point to the remote MCP server.")
    print("Generating this artifact does not replace an already-installed plugin; import/install this marketplace source explicitly.")
    print("This helper is not an OpenAI managed App Template.")
    print("Keep workspace-specific output in an appropriately controlled marketplace source.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a workspace-specific GitLab Self-Hosted ChatGPT marketplace "
            "source bound to an existing app/connector. This is a workspace "
            "binding helper, not an OpenAI managed App Template."
        )
    )
    parser.add_argument(
        "--app-id",
        required=True,
        help="existing ChatGPT workspace app/connector ID",
    )
    parser.add_argument(
        "--mcp-url",
        required=True,
        help="remote HTTPS /mcp endpoint already configured on that app/connector",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="marketplace-source output directory (default: dist/gitlab-chatgpt-marketplace)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace the output directory if it already exists",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    build(validate_app_id(args.app_id), args.mcp_url, args.output, args.force)


if __name__ == "__main__":
    main()
